### ISSUE TITLE
Repositório do tipo Helm

### ISSUE THREAD

**Issue by ruan-oliveira** [nataliagranato/charts#1]
Olá, espero que esteja bem!

O repositório não está funcionando como um repositório Helm. Tentei ativar no meu cliente Helm e não funcionou, veja:

<img width="1461" alt="image" src="https://github.com/nataliagranato/charts/assets/15300032/8eb04101-ba74-4c59-b615-d91cc09bbf8a">

Talvez esses links possam ajudar:
- https://www.opcito.com/blogs/creating-helm-repository-using-github-pages
- https://helm.sh/docs/howto/chart_releaser_action/

Em resumo, este repositório precisará ser ativado como uma github page e está indexado com o Helm para apontamento do artefatos empacotados.

Outra sugestão:
- Orientar o uso por meio de ```git clone <url repo>``` ao invés de ```helm repo add ...```

Me coloco à disposição para apoiar.

**Comment by nataliagranato** [comment]
Olá Ruan, muito obrigada pela contribuição, a action do Github funcionou muito bem, fiz apenas alguns ajustes para charts que possuem dependências. Seguindo o tutorial do primeiro link, mesmo criando o index.yaml  através do helm repo add ele não encontra o arquivo index.yaml:
```

helm repo add techpreta https://github.com/Tech-Preta/charts
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/nataliagranato/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/nataliagranato/.kube/config
Error: looks like "https://github.com/Tech-Preta/charts" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/Tech-Preta/charts/index.yaml : 404 Not Found
```
